import turtle

def turtleLetter(letter,tur):
    if letter=="box":
        tur.setheading(0)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(60)

    elif letter == "A":
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(30)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        #tur.right(180)
    elif letter == "B":
	
        tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(35)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(70)
    elif letter == "C":
	     tur.setheading(0)

        tur.pu()
        tur.left(180)
        tur.pd()
        tur.fd(30)
        tur.left(90)
        tur.fd(50)
        tur.left(90)
        tur.fd(30)
        tur.pu()
        tur.left(90)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
        tur.left(90)
        tur.fd(35)
        tur.right(90)
    elif letter == "D":
	     tur.setheading(0)
        tur.pu()
        tur.fd(5)
        tur.right(90)
        tur.fd(5)
        tur.pd()
        tur.fd(35)
        tur.right(180)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(30)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.right(180)
        tur.fd(15)
        tur.left(90)
        tur.fd(20)
        tur.pu()
        #fixes
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(35)
    elif letter == "E":
	 tur.setheading(0)
	    tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.left(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.fd(10)
        tur.left(90)
        tur.fd(10)
        tur.right(90)
    elif letter == "F":
	tur.setheading(0)
	    tur.pu()
        tur.fd(10)
        tur.right(90)
        tur.fd(10)
        tur.pd()
        tur.fd(40)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.pu()
        tur.fd(10)
        tur.left(90)
        tur.fd(10)
        tur.right(90)
	tur.fd(30)
    elif letter == "G":
	    tur.setheading(0)
	    tur.pu()
	    tur.left(180)
	    tur.pd()
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(50)
	    tur.left(90)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(15)
	    tur.left(90)
	    tur.fd(20)
	    tur.pu()
	    #fixes
	    tur.right(90)
	    tur.fd(20)
	    tur.right(90)
	    tur.fd(35)
	    tur.left(90)
	    tur.fd(15)
	    tur.right(90)
	    #tur.right(180)
    elif letter == "H":
            tur.setheading(0)
	    tur.pu()
	    tur.left(270)
	    tur.pd()
	    tur.fd(50)
	    tur.left(180)
	    tur.fd(25)
	    tur.right(90)
	    tur.fd(30)
	    tur.right(90)
	    tur.fd(25)
	    tur.right(180)
	    tur.fd(50)
	    tur.pu()
	    tur.right(90)
	    tur.fd(20)
    elif letter == "I":
	    tur.setheading(0)
	    tur.pu()
	    tur.left(180)
	    tur.pd()
	    tur.fd(15)
	    tur.right(180)
	    tur.fd(30)
	    tur.left(180)
	    tur.fd(15)
	    tur.left(90)
	    tur.fd(50)
	    tur.right(90)
	    tur.fd(15)
	    tur.right(180)
	    tur.fd(30)
	    tur.pu()
	    tur.fd(20)
	    tur.left(90)
	    tur.fd(50)
	    tur.right(90)
    elif letter == "J":
	    tur.setheading(0)
	    tur.pu()
	    tur.left(180)
	    tur.pd()
	    tur.fd(10)
	    tur.right(180)
	    tur.fd(20)
	    tur.left(180)
	    tur.fd(10)
	    tur.left(90)
	    tur.fd(50)
	    tur.right(90)
	    tur.fd(18)
	    tur.pu()
	    tur.right(180)
	    tur.fd(40)
	    tur.left(90)
	    tur.fd(54)
	    tur.right(90)
    elif letter == "K":
	    tur.setheading(0)
	    tur.pu()
	    tur.left(270)
	    tur.pd()
	    tur.fd(50)
	    tur.right(180)
	    tur.fd(25)
	    tur.right(45)
	    tur.fd(30)
	    tur.right(180)
	    tur.fd(30)
	    tur.left(90)
	    tur.fd(30)
	    tur.pu()
	    tur.left(45)
	    tur.fd(14)
	    tur.left(90)
	    tur.fd(41)
	    tur.right(90)
    elif letter == "L":
        tur.pendown()
        tur.right(90)
        tur.forward(30)
        tur.left(90)
        tur.forward(20)
        tur.penup()
        tur.forward(20)
        tur.left(90)
        tur.forward(30)
        tur.right(90)
    elif letter == "M":
        tur.pendown()
        tur.right(90)
        tur.forward(30)
        tur.penup()
        tur.left(180)
        tur.forward(30)
        tur.right(135)
        tur.pendown()
        tur.forward(20)
        tur.left(90)
        tur.forward(20)
        tur.right(135)
        tur.forward(30)
        tur.penup()
        tur.left(90)
        tur.forward(10)
        tur.left(90)
        tur.forward(30)
        tur.right(90)
   elif letter == "N":
        tur.pendown()
        tur.right(90)
        tur.forward(30)
        tur.penup()
        tur.left(180)
        tur.forward(30)
        tur.right(135)
        tur.pendown()
        tur.forward(40)
        tur.left(135)
        tur.forward(30)
        tur.right(90)
        tur.penup()
        tur.forward(10)
    elif letter == "O":
        tur.pendown()
        tur.forward(40)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.forward(40)
        tur.right(90)
        tur.penup()
        tur.forward(50)
    elif letter =="P":
        tur.pendown()
        tur.forward(15)
        tur.right(90)
        tur.forward(15)
        tur.right(90)
        tur.forward(15)
        tur.left(90)
        tur.forward(25)
        tur.right(180)
        tur.forward(40)
        tur.right(90)
        tur.penup()
        tur.forward(35)		
    elif letter == "Q":
	tur.left(180)
        tur.fd(80)
        tur.left(90)
        tur.fd(80)
        tur.left(90)
        tur.fd(80)
        tur.left(90)
        tur.fd(80)
        tur.right(180)
        tur.fd(80)
        tur.left(45)
        tur.fd(20)
    elif letter == "R":
	 tur.fd(80)
	 tur.right(90)
	 tur.fd(80)
	 tur.right(90)
	 tur.fd(80)
	 tur.right(225)
	 tur.fd(120)
 	 tur.right(180)
	 tur.fd(120)
	 tur.left(135)
	 tur.fd(80)
	 tur.bk(160)
	    
    elif letter == "S":
	   tur.fd(80)
 	   tur.bk(80)
 	   tur.right(90)
 	   tur.fd(80)
 	   tur.left(90)
 	   tur.fd(80)
 	   tur.right(90)
 	   tur.fd(80)
 	   tur.right(90)
 	   tur.fd(80) 
	
    elif letter == "T":
	  tur.fd(80)
	  tur.right(180)
	  tur.fd(40)
	  tur.left(90)
	  tur.fd(80)  
		
    elif letter == "U":
	   tur.right(90)
	   tur.fd(80)
	   tur.left(90)
	   tur.fd(40)
	   tur.left(90)
	   tur.fd(80)
    elif letter == "V":
	tur.pendown()
        tur.right(45)
        tur.fd(30)
        tur.right(270)
        tur.fd(30)
        tur.penup()
        tur.right(90)
        tur.fd(30)
    elif letter == "W":
	tur.pendown()
        tur.right(45)
        tur.fd(30)
        tur.right(270)
        tur.fd(30)
        tur.pendown()
        tur.right(90)
        tur.fd(30)
        tur.right(270)
        tur.fd(30)
        tur.penup()
        tur.right(90)
        tur.fd(30)
    elif letter == "X":
	tur.pendown()
        tur.right(45)
        tur.fd(40)
        tur.left(180)
        tur.fd(20)
        tur.right(90)
        tur.fd(20)
        tur.left(180)
        tur.fd(40)
        tur.penup()
        tur.right(180)
        tur.fd(40)
        tur.right(90)
        tur.fd(30)
    elif letter == "Y":
	 tur.pendown()
        tur.right(45)
        tur.fd(20)
        tur.right(45)
        tur.fd(20)
        tur.left(180)
        tur.fd(20)
        tur.right(45)
        tur.fd(20)
        tur.penup()
        tur.right(90)
        tur.fd(30)
    elif letter == "Z":
	tur.pendown()
        tur.right(360)
        tur.fd(30)
        tur.right(135)
        tur.fd(30)
        tur.right(225)
        tur.fd(30)
        tur.penup()
        tur.left(90)
        tur.fd(30)

    elif letter == "Ax":
        # code here
        tur.forward(40)
		
    else:
        turtleLetter("box",tur)
	







window = turtle.Screen()
tur = turtle.Turtle()
tur.speed(1)
#turtleLetter("box",tur)
turtleLetter("A",tur)


window.exitonclick()
